
name: Reusable workflow to Deploy Artifacts to GCP App engine 

on:
  workflow_call:
    inputs:
      workload_identity_provider:
        type: string
        required: true
      service_account:
        type: string
        required: true
      audience:
        type: string
        required: true
  
    outputs:
      app_url:
        description: "Url of the deployed app"
        value: ${{ jobs.deploy_to_app.outputs.app_url }}

permissions:
  id-token: write
  contents: read
  
jobs:
  deploy_to_app:
    runs-on: ubuntu-latest
    outputs:
      app_url: ${{ steps.deploy.outputs.url }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - run: git pull
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: ${{inputs.workload_identity_provider}}
        service_account: ${{inputs.service_account}}
        audience: ${{inputs.audience}}
    
    - run: |
        ls
        node --version        
        
#         workload_identity_provider: 'projects/39305491180/locations/global/workloadIdentityPools/node-workload-identity/providers/gh-app-engine'
#         service_account: 'gcp-app-engine-user@third-wharf-342109.iam.gserviceaccount.com'
#         audience: 'https://github.com/raju-dasupally'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v0'

    - name: Post deployment Status
      if: always()
      uses: tauhid621/post-deployment-status@main
      env:
        DEP_URL: ${{ steps.deploy.outputs.url }}
        SLACK_CHANNEL_SECRET: ${{ SECRETS.SLACK_CHANNEL_SECRET }}
