name: "deploy"
on:
  workflow_dispatch

permissions:
   id-token: write
   contents: write

jobs:
  deploy: 
    runs-on: ubuntu-latest
    name: "Deploy nodejs app to GCP app engine"
    environment:
       name: development
       url: ${{ steps.get-url.outputs.your_site }}
    
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "package.json"
      
      - name: use node.js v14
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          check-latest: true
          registry-url: https://registry.npmjs.org/

      - name: Stacks framework code generation
        run: |
          npx express-generator expressjs-scaffold
          cp -r expressjs-scaffold/* .
          rm -rf expressjs-scaffold
#       - name: Run npm build
#         run: |
#           npm run build

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/39305491180/locations/global/workloadIdentityPools/node-workload-identity/providers/gh-app-engine'
          service_account: 'gcp-app-engine-user@third-wharf-342109.iam.gserviceaccount.com'
          audience: 'https://github.com/raju-dasupally'

#       - name: 'Deploy to App Engine'
#         run: 'gcloud app deploy app.yaml --quiet --no-promote --version v1'
      - id: 'deploy'
        uses: 'google-github-actions/deploy-appengine@v0'
        
      - name: Post deployment Status
        if: always()
        uses: tauhid621/post-deployment-status@main
        env:
          DEP_URL: ${{ steps.deploy.outputs.url }}
          SLACK_CHANNEL_SECRET: ${{ SECRETS.SLACK_CHANNEL_SECRET }}
